### ISSUE TITLE
seed data up-to-date

### ISSUE THREAD

**Issue by JX-Wang** [stanford-esrg/gps#1]
Hello.

Seems that the seed data your team provided has been deleted and the data is too old to get realiable prediction results, could your team please provide some up-to-date seed data for us to do some experiments?

Thanks.

**Comment by LizIzhikevich** [comment]
I have restored the original link to the April 2021 seed data. Unfortunately, this is the most recent seed data that I have so far that samples all 65K ports at 1%. While this seed will still pick up larger patterns, I agree that it will not pick up the most recent ones. I think you will have to run your own scans to make an up-to-date seed. When my lab compiles a new seed, I will update the link.
